### ISSUE TITLE
unknown setting [xpack.security.enabled]

### ISSUE THREAD

**Issue by ohadlahav** [beshu-tech/readonlyrest-docs#18]
As described in the docs, tried to set
xpack.security.enabled: false but es fail to start

`java.lang.IllegalArgumentException: unknown setting [xpack.security.enabled] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
`
Any ideas ?
Thanks

**Comment by rsmith013** [comment]
Which version of elasticsearch are you using? In versions 6.2 and older, x-pack was a separate installation. 6.3 and newer, x-pack comes with your installation and that setting should work.
