### ISSUE TITLE
Documentation still mentions elasticsearch.yml as the target for rules

### ISSUE THREAD

**Issue by trondhindenes** [beshu-tech/readonlyrest-docs#2]
It is my understanding that the recommended place to put rules is a separate config file. However, most documentation still describes adding rules to elasticsearch.yml.

**Comment by sahil-sharma** [comment]
Yes. And, if we put rules in elasticsearch,yml file then we may face errors. But, if we put rules in a separate file as readonlyrest.yml then it works fine.
