### ISSUE TITLE
Documented Examples for proxy_auth dont work

### ISSUE THREAD

**Issue by CyberTaoFlow** [beshu-tech/readonlyrest-docs#29]
The documented structure of ACL blocks seems to have changed significantly between 1.16 and 1.18 however this is not clearly documented in these docs.

Some examples: 
Error seen:
 

> org.elasticsearch.bootstrap.StartupException: StartingFailureException[Errors:

> Malformed settings: proxy_auth:

>- "*"
>x_forwarded_for:
>- "*"

So it would seem that 
```proxy_auth: ["*"]```
or 
```proxy_auth: *```

are no longer valid under 1.18.  Instead it seems the config is now to be expressed using sub components like:
```
      proxy_auth: 
        users: ["*"]
        proxy_auth_config: "someconf"
```
and a seperate top level section:
```
 proxy_auth_configs:

    - name: "someconf"
      user_id_header: "x-forwarded-user"
```

Another error I have encountered is :
```
No order defined for rule: hosts
```
this seems like a warning as things still start however this is not documented and I have no idea how to resolve...

**Comment by sscarduzio** [comment]
@coutoPL WDYT?

**Comment by coutoPL** [comment]
@CyberTaoFlow yes you are right. It's a bug, because we want to be always backward compatible. I'll fix it and let you know (please, give us a hint what ES version you use - I'll send proper build).

by now, you can fix it like this:
```
proxy_auth:
  users: ["*"]
```

**Comment by coutoPL** [comment]
it's fixed and merged. Will be released soon together with other changes and fixes in ROR 1.18.8.
Thanks for report once again. 

@sscarduzio we can close the issue

**Comment by CyberTaoFlow** [comment]
Im using 6.5.4 currently.   I will look out for 1.18.8  enterprise and follow up here.  I am happy to migrate the config to the new format but its just not documented anywhere except the plugin repo via commit comments and code review. 

I found the test cases especially informative :)

**Comment by coutoPL** [comment]
@sscarduzio  this is done
