### ISSUE TITLE
"Add" button not visible in discover for RO users

### ISSUE THREAD

**Issue by sirdrug** [beshu-tech/readonlyrest-docs#45]
Good day! In the latest version of the plugin, users who have kibana_access: ro rights have lost the ability to add fields in the Discover tab, the add button has disappeared. Why is this done? Can you add a setting to return it?

![2020-02-25_12-53-06](https://user-images.githubusercontent.com/29921002/75235758-d021a700-57cd-11ea-8ed4-fe780b0b8f43.png)

**Comment by Simakink** [comment]
+1

**Comment by iru-dev** [comment]
+1

**Comment by sscarduzio** [comment]
This is tracked in the forum: https://forum.readonlyrest.com/t/kibana-lost-button-add-in-discovery-panel/1460
