### ISSUE TITLE
_clone, _shrink API don't work 

### ISSUE THREAD

**Issue by sirdrug** [beshu-tech/readonlyrest-docs#67]
{
  "error" : {
    "root_cause" : [
      {
        "reason" : "forbidden",
        "due_to" : [
          "OPERATION_NOT_ALLOWED"
        ]
      }
    ],
    "reason" : "forbidden",
    "due_to" : [
      "OPERATION_NOT_ALLOWED"
    ],
    "status" : 401
  }
}

**Comment by sirdrug** [comment]
Fix, this problem please in future release!

**Comment by coutoPL** [comment]
For sure it will be fixed. Will let you know

**Comment by coutoPL** [comment]
@sirdrug we have a fix for _clone (and potentially for _shrink too). Are you interested in ROR pre-build for tests? If so, please let us know what ES version are you currently using
