### ISSUE TITLE
Option to disable loading settings from .readonlyrest

### ISSUE THREAD

**Issue by jpmckinney** [beshu-tech/readonlyrest-docs#78]
https://github.com/beshu-tech/readonlyrest-docs/blob/master/kibana.md

Setting `force_load_from_file: true` doesn't prevent "Loading ReadonlyREST settings from index" later. When that index doesn't exist, it takes a lot longer for "ReadonlyREST core was loaded" to be reached.

I think something I can do in the meantime is set "com.readonlyrest.settings.loading.delay". Where do I set this? In a jvm.options.d file?

**Comment by jpmckinney** [comment]
Note that I'm only using the plugin for Elasticsearch – I don't use Kibana.

Creating an empty `.readonlyrest` index just causes a failure, so that's not a workaround.

**Comment by jpmckinney** [comment]
Aha. I can do, in `/etc/elasticsearch/jvm.options.d/readonlyrest.options`:

```
-Dcom.readonlyrest.settings.loading.delay=1
```

So now ROR will only take 5 seconds to give up finding the index, instead of 25 seconds.

**Comment by fbaligand** [comment]
@jpmckinney 

The force_load_from_file: true setting has to be set in elasticsearch.yml, not in readonlyrest.yml. ROR reads elasticsearch.yml first and then decides if it should load settings from index or from file. 
Explained here in the docs:
https://github.com/beshu-tech/readonlyrest-docs/blob/master/kibana.md#malformed-in-index-settings

**Comment by jpmckinney** [comment]
It would be good to mirror that explanation in `elasticsearch.md`, because I'm not using Kibana at all, and I only ended up on that page by searching the repo for "Loading ReadonlyREST settings from index".

**Comment by fbaligand** [comment]
Well, actually, I'm not readonlyrest team member :)
I just opened recently an issue about that on readonlyrest core repository:
https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/issues/683

And then, I just give you back the information I got.

**Comment by sscarduzio** [comment]
@jpmckinney ROR documenation is open source, and you can propose the change to [elasticsearch.md](https://github.com/beshu-tech/readonlyrest-docs/blob/master/elasticsearch.md) without leaving the Github website. I will be happy to approve it!

And yeah, @fbaligand is one of the most seasoned ROR community member, you will see his name a lot in our [forum](forum.readonlyrest.com/) too.

**Comment by fbaligand** [comment]
Thanks @sscarduzio :)
And thanks for your awesome work on this great plugin!

**Comment by jpmckinney** [comment]
I'm satisfied with the information in the issue - just a suggestion for what might help others, though now that this issue exists, they might similarly find the answer here :)

**Comment by jpmckinney** [comment]
Also, anyone searching the docs might find the relevant content in kibana.md. now that it's been corrected: https://github.com/beshu-tech/readonlyrest-docs/commit/bc6e14e3e99d1065bb8c35638c9236843522ebf5
