### ISSUE TITLE
Config locations and environment variables.

### ISSUE THREAD

**Issue by pemontto** [beshu-tech/readonlyrest-docs#8]
I just started using this plugin before committing to the enterprise version. Getting started wasn't as obvious as I was expecting for version 6.

The documentation seems to indicate $ES_HOME is the appropriate place for configuration. As far as I'm aware $ES_HOME usually point to the executable location, not where the config should go. This would give me `Could not find required attribute 'readonlyrest'`
I believe for version 6 at least it should be $ES_PATH_CONF or $CONF_DIR instead of $ES_HOME.

Putting readonlyrest.yml under $ES_PATH_CONF works correctly for me.

```
# echo $ES_HOME
/usr/share/elasticsearch
```
```
# echo $ES_PATH_CONF
/etc/elasticsearch
```

Happy to update the docs, just not sure how you want to handle covering discrepancies between versions.

**Comment by sscarduzio** [comment]
Nicely noted, sir. Will amend. Sorry took so long.
